-- Create a Third Party Extension for UUID
CREATE EXTENSION "uuid-ossp";

CREATE TABLE tblUser
(
	UserId bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
	UserIdentity UUID DEFAULT uuid_generate_v4(),
	Info JSON
)